### ISSUE TITLE
Backend CSS-Style

### ISSUE THREAD

**Issue by wiesson** [menatwork-ia/valumsFileUploader#41]
Im Backend ist sind ein paar Style-Definitionen gesetzt, die würde ich gerne in die valumsFileUploader.css auslagern. Leider finde ich die folgenden Style definitionen nicht: 

``` html

<input multiple="multiple" type="file" name="file" 
style="position: absolute; right: 0px; top: 0px; font-family: Arial; font-size: 118px; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; cursor: pointer; opacity: 0; ">

```

könnte in die valumsFileUploader.css mit:

``` CSS

#file-uploader.backend input {
    position: absolute; 
    right: 0px; 
    top: 0px;
    cursor: pointer; 
    opacity: 0;
    margin: 0;
    font: 118px Arial;
    padding: 0;
  }

```

Die Schriftgröße von  118px finde ich recht fraglich ;)
